# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.4
    working_directory: ~/working

    steps:
      - checkout
      - run: npm install
      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job. 
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
          # taken to be the root directory of the workspace.
          root: ~/working
          # Must be relative path from root
          paths:
            - package.json
  deploy_integration:
    docker:
      - image: circleci/node:12.4
    steps:
      - run: echo "Deployed Integration"
  deploy_staging:
    docker:
      - image: circleci/node:12.4
    steps:
      - run: echo "Deployed Staging"
  deploy_prod:
    docker:
      - image: circleci/node:12.4
    steps:
      - run: echo "Deployed! Prod"

workflows:
  version: 2
  ci:
    jobs:
      - build:
          filters:
            branches:
              ignore: 
                - master
  cd:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - master
      - deploy_integration:
          requires:
            - build
      - hold_staging:
          type: approval
          requires:
            - deploy_integration
      - deploy_staging:
          requires:
            - hold_staging
      - hold_prod:
          type: approval
          requires:
            - deploy_staging
      - deploy_prod:
          requires:
            - hold_prod
